apiVersion: v1
kind: Service
metadata:
  name: mon-db
  namespace: mon-pub
spec:
  ports:
    - port: 5432
  selector:
    app: mon-db
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mon-db
  namespace: mon-pub
spec:
  serviceName: "mon-db"
  replicas: 1
  selector:
    matchLabels:
      app: mon-db
  template:
    metadata:
      labels:
        app: mon-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: mon-config
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: mon-config
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mon-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: mon-pgdata
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "iu_parsers", "-d", "iu_parsers"]
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "iu_parsers", "-d", "iu_parsers"]
            initialDelaySeconds: 5
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: mon-pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
